"""Database creation

Revision ID: d605dbb26927
Revises: 5495ee4f2161
Create Date: 2024-02-28 07:49:36.817978

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd605dbb26927'
down_revision: str | None = '5495ee4f2161'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sub_menu',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('main_menu_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['main_menu_id'], ['main_menu.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'dishes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('sub_menu_id', sa.Integer(), nullable=False),
        sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
        sa.ForeignKeyConstraint(['sub_menu_id'], ['sub_menu.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    op.drop_table('sub_menu')
    # ### end Alembic commands ###
